config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items
  root "items#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  mount_uploader :image_url, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource
  before_action :configure_permitted_parameters, if: :devise_controller?

  def layout_by_resource
    if devise_controller?
      "layout_for_devise"
    else
      "application"
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: [:show, :destroy, :edit, :update]

  def index
    @items = Item.where("user_id = ? and name LIKE(?)",current_user.id, "%#{params[:keyword]}%").page(params[:page]).per(12)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def show
  end

  def new
    @item = Item.new
  end

  def create
    Item.create(create_params)
    redirect_to action: :index
  end

  def destroy
    @item.destroy if @item.user_id == current_user.id
    redirect_to action: :index
  end

  def update
    @item.update(create_params) if @item.user_id == current_user.id
    redirect_to action: :index
  end

  def edit
  end

  private
  def create_params
    params.require(:item).permit(:name,:image_url,:storage,:memo).merge(user_id:current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if User.find(current_user.id).update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/edit.haml
.contents
  .form_field
    %h2 アイテム編集
    = render partial: 'shared/itemForm', locals: { item: @item }

app/views/items/index.haml
.contents
  .itemList
    - @items.each do |item|
      = render partial: 'shared/item', locals: { item: item }
  .loadingBox
    .loadingImageScroll

app/views/items/new.haml
.contents
  .form_field
    %h2 新規アイテム登録
    = render partial: 'shared/itemForm', locals: { item: @item }

app/views/items/show.haml
.contents
  .itemDetail{ data: {id: "#{@item.id}"}}
    .itemDetail__itemImage{style: "background-image: url('#{ @item.image_url.url}') "}
    .itemDetail__itemName="アイテム名: #{ @item.name }"
    .itemDetail__itemStorage="保管場所: #{ @item.storage }"
    .itemDetail__itemMemo="メモ: #{ @item.memo }"
    .itemDetail__itemQR=image_tag("https://chart.apis.google.com/chart?cht=qr&chs=200x200&chl=#{url_for(only_path: false)}")

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MaterialGarage
    = csrf_meta_tags
    = csp_meta_tag
    %meta{ name: 'viewport', content: "width=device-width, initial-scale=1,user-scalable=no" }

    %link{ rel: "stylesheet", href: "https://use.fontawesome.com/releases/v5.6.1/css/all.css" }
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .preload_image
    .mainImageWrapper
    .modalWindow
      .mobileMenu
        %label{name:"title"}
        %input{name:"title", placeholder:"検索", class: "searchInputSide"}
        =link_to 'アイテム追加', new_item_path
        =link_to 'ユーザー情報', edit_user_registration_path
        =button_to 'ログアウト', destroy_user_session_path, method: :delete
    .wrapper
      %header.header
        .logo
          =link_to 'Material Garage', '/'
        .serchBox
          %label{name:"title"}
          %input{name:"title", placeholder:"検索", class: "searchInput"}
        .nemu
          -if user_signed_in?
            .nemu__humburgerMenu
              = link_to "#" do
                %i.fa.fa-bars
            .nemu__action
              =link_to 'アイテム追加', new_item_path
            .nemu__action
              =link_to 'ユーザー情報', edit_user_registration_path
            .nemu__action
              =link_to 'ログアウト', destroy_user_session_path, method: :delete
      = yield
      %footer.footer
        ="© 2018 - #{Time.now.year} Material Garage ALL RIGHTS RESERVED."

app/views/layouts/layout_for_devise.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MaterialGarage
    = csrf_meta_tags
    = csp_meta_tag
    %meta{ name: 'viewport', content: "width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" }

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .preload_image
    .DeviseImageWrapper
    .wrapper
      %header.header
        .logo--devise
          =link_to 'Material Garage', '/'
          %p サンプル・素材の管理を簡単に
      .contents
        .form_field
          = yield
      %footer.footer
        ="© 2018 - #{Time.now.year} Material Garage ALL RIGHTS RESERVED."

app/views/shared/_item.haml
.itemList__element.element{ data: {id: "#{item.id}"}}
  .element__itemImage{style: "background-image: url('#{ item.image_url.url}') "}
  =link_to "#{item.name}",item_path(item.id), class: "element__itemName"
  .element__itemStorage=item.storage
  %hr
  =link_to "削除",item_path(item.id), class: "element__itemDelete", method: :delete
  =link_to "編集",edit_item_path(item.id), class: "element__itemEdit"
  =link_to "",item_path(item.id), class: "element__itemLink"

app/views/shared/_itemForm.haml
= form_for item do |f|
  .field
    = f.label :name, "名前"
    = f.text_field :name, autofocus: true, autocomplete: "name"
  .field
    = f.label :image_url,"イメージファイルを選択", for: "fileUpload", class: "fileLabel"
    = f.file_field :image_url, autofocus: true, autocomplete: "image_url", id: "fileUpload"
    = image_tag item.image_url.url, id: "img_prev" if item.image_url?
  .field
    = f.label :storage, "保管場所"
    = f.text_field :storage, autofocus: true, autocomplete: "storage"
  .field
    = f.label :memo, "メモ"
    = f.text_field :memo, autofocus: true, autocomplete: "memo"
  .actions
    = f.submit "登録"
= link_to "戻る", :back